Revert "libxc/uxendm: change xc_translate_foreign_address api to operate on range"
This reverts commit 1826d43b2f404f530ec29ab923d8993fab4ea91f.

This breaks the build:

Compiling - xenctx.o
c:/dev/uxen/xen/common/xen-tools/xentrace/xenctx.c: In function 'map_page':
c:/dev/uxen/xen/common/xen-tools/xentrace/xenctx.c:457:9: error: implicit declaration of function 'xc_translate_foreign_address'